RISK_WEIGHTS = {
    "MISSING_CRITICAL_CLAUSE": 3.0,
    "LOW_CONFIDENCE_CRITICAL_CLAUSE": 0.5,
    "ONE_SIDED_OBLIGATION": 2.5,
    "WEAK_TERMINATION_RIGHTS": 3.0,
    "LONG_TERM_COMMITMENT": 1.5,
    "AMBIGUOUS_GRANT": 1.0
}
